name: brew test-bot
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Ensure CI uses this PR's files (tap local workspace and force checkout PR SHA)
        shell: bash
        run: |
          set -euxo pipefail

          brew update-reset
          brew untap ${{ github.repository }} || true

          # Tap from the workspace (Homebrew will still clone into its Taps dir)
          brew tap ${{ github.repository }} "$GITHUB_WORKSPACE"
          TAP_PATH="$(brew --repo ${{ github.repository }})"

          # Force the tap repo to the PR/MR SHA we just checked out
          # (Homebrew otherwise checks out the default branch of the tap)
          git -C "$TAP_PATH" fetch --force "$GITHUB_WORKSPACE" \
            "+${GITHUB_SHA}:refs/heads/ci-pr"
          git -C "$TAP_PATH" checkout -f ci-pr

          echo "Workspace HEAD: $(git -C "$GITHUB_WORKSPACE" rev-parse HEAD)"
          echo "Tap HEAD:       $(git -C "$TAP_PATH" rev-parse HEAD)"

          # Sanity: show the formulas Homebrew will read
          ls -la "$TAP_PATH/Formula" || true
          for f in "$TAP_PATH"/Formula/*.rb; do
            echo "=== $(basename "$f")"
            sed -n '1,100p' "$f"
            echo
          done

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'
        env:
          HOMEBREW_NO_INSTALL_FROM_API: 1

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles
          path: '*.bottle.*'
